name: Foundry Release Upload

on:
  release:
    types:
      - published

jobs:
  foundry_release_upload:
    runs-on: ubuntu-latest
    name: Foundry Release Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: foundryvtt-dcc/dcc-content
          token: ${{ secrets.FOUNDRY_PUBLISHER_TOKEN }}

      - name: Foundry Release Upload
        id: foundry-release-upload
        uses: foundryvtt-dcc/foundry-release-upload-action@main
        with:
          actionToken: ${{ secrets.FOUNDRY_PUBLISHER_TOKEN }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsAccessSecret: ${{ secrets.AWS_ACCESS_SECRET }}
          awsBucketName: ${{ secrets.AWS_BUCKET_NAME }}
          awsBucketRegion: ${{ secrets.AWS_BUCKET_REGION }}
          manifestFileName: 'module.json'
